<?php  //[STAMP] 46c9b1a0c4b15534ec95bdb90031c467
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait DepartamentoTestActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
